### ISSUE TITLE
TypeError: handlePacket() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by CeePee1974** [jamesremuscat/pcars#8]
Hi,

I am trying to run your API using the "Quickstart" code you provide (just so that i know everything is working) and I get the following error message:

_Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/cwprice/Documents/Python/pcars-master/src/pcars/stream.py", line 35, in run
    listener.handlePacket(packet)
TypeError: handlePacket() takes exactly 1 argument (2 given)_

The above error is thrown instantly that PCars sends a UDP packet. I have tried running the API with both Python 2.7 and 3.6 but I still get the same error. Do you have any ideas as to what might be causing this?

Many thanks,

Chris.

**Comment by jamesremuscat** [comment]
Ah - that will teach me to write example code without testing it!

The definition of `handlePacket` in the sample is missing a `self` argument. So it should be, in full:

```python
from pcars.stream import PCarsStreamReceiver

class MyPCarsListener(object):
    def handlePacket(self, data):
        # You probably want to do something more exciting here
        # You probably also want to switch on data.packetType
        # See listings in packet.py for packet types and available fields for each
        print data


listener = MyPCarsListener()
stream = PCarsStreamReceiver()
stream.addListener(listener)
stream.start()
```
